# Import the libraries required 
1.Pandas<br>
2.NumPy<br>
3.MatplotLib<br>
4.SKLearn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [ ]:
iris=load_iris()

In [ ]:
dt=iris.data
tar=iris.target
col=iris.feature_names

# Create a example data frame

In [ ]:
fd=pd.DataFrame(iris.data)
fd.columns=col

In [ ]:
fd.tail(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

# To detect and remove outliers these are the following ways.
1.Scatter plot<br>
2.Box plot<br>
3.Z-Score<br>
4.IQR<br>

# filter only the numeric values

In [ ]:
from sklearn.datasets import load_boston
#Load the data
boston = load_boston()

#Find features and target
x = boston.data
y = boston.target
boston_df = pd.DataFrame(boston.data)
columns = boston.feature_names
boston_df.columns = columns
df = boston_df
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

newdf = df.select_dtypes(include=numerics)

In [ ]:
newdf

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

# here we are using z score for detecting and removing outliers.

In [ ]:
num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

newfd = fd.select_dtypes(include=num)

In [ ]:
newfd

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
from scipy import stats
z=np.abs(stats.zscore(newdf))

In [ ]:
z

array([[0.41978194, 0.28482986, 1.2879095 , ..., 1.45900038, 0.44105193,
        1.0755623 ],
       [0.41733926, 0.48772236, 0.59338101, ..., 0.30309415, 0.44105193,
        0.49243937],
       [0.41734159, 0.48772236, 0.59338101, ..., 0.30309415, 0.39642699,
        1.2087274 ],
       ...,
       [0.41344658, 0.48772236, 0.11573841, ..., 1.17646583, 0.44105193,
        0.98304761],
       [0.40776407, 0.48772236, 0.11573841, ..., 1.17646583, 0.4032249 ,
        0.86530163],
       [0.41500016, 0.48772236, 0.11573841, ..., 1.17646583, 0.44105193,
        0.66905833]])

# **from the z score we know that the outliers are greater than 3.**

In [ ]:
np.where(z>3)

(array([ 55,  56,  57, 102, 141, 142, 152, 154, 155, 160, 162, 163, 199,
        200, 201, 202, 203, 204, 208, 209, 210, 211, 212, 216, 218, 219,
        220, 221, 222, 225, 234, 236, 256, 257, 262, 269, 273, 274, 276,
        277, 282, 283, 283, 284, 347, 351, 352, 353, 353, 354, 355, 356,
        357, 358, 363, 364, 364, 365, 367, 369, 370, 372, 373, 374, 374,
        380, 398, 404, 405, 406, 410, 410, 411, 412, 412, 414, 414, 415,
        416, 418, 418, 419, 423, 424, 425, 426, 427, 427, 429, 431, 436,
        437, 438, 445, 450, 454, 455, 456, 457, 466]),
 array([ 1,  1,  1, 11, 12,  3,  3,  3,  3,  3,  3,  3,  1,  1,  1,  1,  1,
         1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5,  3,  3,  1,  5,
         5,  3,  3,  3,  3,  3,  3,  1,  3,  1,  1,  7,  7,  1,  7,  7,  7,
         3,  3,  3,  3,  3,  5,  5,  5,  3,  3,  3, 12,  5, 12,  0,  0,  0,
         0,  5,  0, 11, 11, 11, 12,  0, 12, 11, 11,  0, 11, 11, 11, 11, 11,
        11,  0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11

In [ ]:
newdf.shape

(506, 13)

In [ ]:
zdf=newdf[(z<3).all(axis=1)]

In [ ]:
zdf.shape

(415, 13)

# writing a function to remove outliers  using z score

In [ ]:
!pip install datacleaner

# auto cleans the real word data and convert back to csv if it has to be cleaned


In [ ]:
from datacleaner import autoclean
import pandas as pd

my_data = pd.read_csv('my_data.csv', sep=',')
my_clean_data = autoclean(my_data) # inbuilt function in data cleaner to clean the data
my_data.to_csv('my_clean_data.csv', sep=',', index=False)

In [ ]:
def rmout(fd):
  num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64'] # to take only numerics
  newfd = fd.select_dtypes(include=num)  # take only numeric columns
  z=np.abs(stats.zscore(newfd)) #import scipy from scipy use the Zscore
  zdf=newfd[(z<3).all(axis=1)] # create a data frame with less than Zscore of 3 to remove the outliers.
  #remainingdatatypes=['object','bool_','datetime64[ns]'] 
  #fdf=fd.select_dtypes(include=num)
  # if youu need cocatenation 
  #finaldf=pd.concat([zfd,fdf], axis=1)# use this line of code.
  return zdf



df.head()

In [ ]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
s=rmout(df)

In [ ]:
s

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[415 rows x 13 columns]

# Function for subtracction of dates


In [ ]:
from datacleaner import autoclean
import pandas as pd

my_data = pd.read_csv('my_data.csv', sep=',')
my_clean_data = autoclean(my_data) # inbuilt function in data cleaner to clean the data
my_data.to_csv('my_clean_data.csv', sep=',', index=False)

In [ ]:
def datesub(df):
  for co in df.columns: # create a for loop to see the objects which are date
    if df[co].dtype == 'object':
        try:
            df[co] = pd.to_datetime(df[co]) # finds the data frame that is date
        except ValueError:
            pass
  num = ['datetime64[ns]'] #list to take a string to filter
  newfd = df.select_dtypes(include=num) #takes only date column
  for i in newfd: # for loop to perform the subtraction
    for j in newfd:
      if(i!=j):
        if(i<j):
        #print(i,j)
          newfd[i+'-'+j]=newfd[i]-newfd[j]
  #remainingdatatypes=['object',int16', 'int32', 'int64', 'float16', 'float32', 'float64] 
  #fdf=fd.select_dtypes(include=num)
  # if youu need cocatenation 
  #finaldf=pd.concat([fdf,newdf], axis=1)# use this line of code.
  return newfd # finally returns a data frame with subtracted columns

# function for removing columns in pearson correlation


In [ ]:
from datacleaner import autoclean
import pandas as pd

my_data = pd.read_csv('my_data.csv', sep=',') # give a real worlsd file to clean 
my_clean_data = autoclean(my_data) # inbuilt function in data cleaner to clean the data
my_data.to_csv('my_clean_data.csv', sep=',', index=False) # you will get world real data clear

In [ ]:
def correlation(dataset, threshold):
    num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    newfd = dataset.select_dtypes(include=num)
    col_corr = set() # Set of all the names of deleted columns
    corr_matrix = newfd.corr(method ='pearson')
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j] >= threshold) and (corr_matrix.columns[j] not in col_corr):
                colname = corr_matrix.columns[i] # getting the name of column
                col_corr.add(colname)
                if colname in dataset.columns:
                    del dataset[colname] # deleting the column from the dataset
  #remainingdatatypes=['object',int16', 'int32', 'int64', 'float16', 'float32', 'float64] 
  #fdf=fd.select_dtypes(include=num)
  # if youu need cocatenation 
  #finaldf=pd.concat([fdf,newdf], axis=1)# use this line of code.
    print(dataset)